config/routes.rb
Weibo::Application.routes.draw do
  resources :tags

  match 'users/upload_photo' => 'users#upload_photo'
  match 'users/submit_upload' => 'users#submit_upload', :via => 'post'
  match 'users/login' => 'users#login'
  match 'users/submit_login' => 'users#submit_login', :via => 'post'
  match 'users/logout' => 'users#logout'
  match 'users/tweets/:id' => 'users#tweets'
  match 'users/followers/:id' => 'users#followers'
  match 'users/follower/:id' => 'users#followers'
  match 'users/following/:id' => 'users#following'
  match 'users/followings/:id' => 'users#following'
  match 'users/add_following/:id' => 'users#add_following'
  match 'users/del_follower/:id' => 'users#del_follower'
  match 'users/del_following/:id' => 'users#del_following'
  match 'users/all' => 'users#all'
  match 'users/search' => 'users#search'
 
  resources :tags
  resources :tweets
  resources :users

  root :to => 'users#index'

end

app/models/tweet.rb
class Tweet < Neo4j::Rails::Model
  property :tweet_id, :type => String, :index => :exact
  property :text, :type => String, :index => :exact
  property :image, :type => String
  property :date, :type => DateTime, :index => :exact
  property :user_id, :type=>String
  
  def to_s
    tweet_id
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # GET /tweets
  # GET /tweets.json
  def index
    @current_user = User.find(session[:user_id])
    @tweets = @current_user.outgoing(:following).outgoing(:tweets).depth(2).filter{|path| path.length == 2}

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @tweets }
    end
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @tweet = Tweet.find(params[:id])
    @tweet.sort!{|a,b| a.date <=> b.date}
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @tweet }
    end
  end

  # GET /tweets/new
  # GET /tweets/new.json
  def new
    @tweet = Tweet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @tweet }
    end
  end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet      = Tweet.new(params[:tweet])
    @tweet.date = DateTime.now
    @user       = User.find(session[:user_id])
    @tweet.user_id = session[:user_id]
    @user.tweets << @tweet
    @user.save!
    respond_to do |format|
      if @tweet.save
	@tweet.save!
        format.html { redirect_to '/' }
        format.json { render :json => @tweet, :status => :created, :location => @tweet }
      else
        format.html { render :action => "new" }
        format.json { render :json => @tweet.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tweets/1
  # PUT /tweets/1.json
  def update
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      if @tweet.update_attributes(params[:tweet])
        format.html { redirect_to @tweet, :notice => 'Tweet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @tweet.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @user = User.find(session[:user_id])
    @tweet = Tweet.find(params[:id])
    @user.tweets.delete(@tweet)
    @tweet.destroy
    @user.save
    respond_to do |format|
      format.html { redirect_to "/users/tweets/#{session[:user_id]}"}
      format.json { head :no_content }
    end
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tweet_id %><br />
    <%= f.text_field :tweet_id %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h1>Listing tweets</h1>

<table>
  <tr>
    <th>Tweet</th>
    <th>Text</th>
    <th>Image</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tweets.each do |tweet| %>
  <tr>
    <td><%= tweet.tweet_id %></td>
    <td><%= tweet.text %></td>
    <td><%= tweet.image %></td>
    <td><%= tweet.date %></td>
    <td><%= link_to 'Show', tweet %></td>
    <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
    <td><%= link_to 'Destroy', tweet, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tweet:</b>
  <%= @tweet.tweet_id %>
</p>

<p>
  <b>Text:</b>
  <%= @tweet.text %>
</p>

<p>
  <b>Image:</b>
  <%= @tweet.image %>
</p>

<p>
  <b>Date:</b>
  <%= @tweet.date %>
</p>


<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>