config/routes.rb
Weibo::Application.routes.draw do
  resources :tags

  match 'users/upload_photo' => 'users#upload_photo'
  match 'users/submit_upload' => 'users#submit_upload', :via => 'post'
  match 'users/login' => 'users#login'
  match 'users/submit_login' => 'users#submit_login', :via => 'post'
  match 'users/logout' => 'users#logout'
  match 'users/tweets/:id' => 'users#tweets'
  match 'users/followers/:id' => 'users#followers'
  match 'users/follower/:id' => 'users#followers'
  match 'users/following/:id' => 'users#following'
  match 'users/followings/:id' => 'users#following'
  match 'users/add_following/:id' => 'users#add_following'
  match 'users/del_follower/:id' => 'users#del_follower'
  match 'users/del_following/:id' => 'users#del_following'
  match 'users/all' => 'users#all'
  match 'users/search' => 'users#search'
 
  resources :tags
  resources :tweets
  resources :users

  root :to => 'users#index'

end

app/models/user.rb
class User < Neo4j::Rails::Model
  property :id, :type => String, :index => :exact
  property :name, :type => String, :index => :fulltext
  property :email, :type => String, :index => :exact
  property :password, :type => String
  property :location, :type => String
  property :gender, :type => String
  property :blog, :type => String
  property :intro, :type => String
  property :qq, :type => String
  property :msn, :type => String
  property :img, :type => String
  has_n :user_tags
  has_n :followers
  has_n :following
  has_n :tweets
  
  validates_presence_of :name
  validates_presence_of :email
  validates_uniqueness_of  :email

  #attr_accssor :password_confirmation
  #validates_confirmation_of:password
  #validate :password_non_blank
  
  def password_non_blank
     errors.add(:password,"Missing password") if password.blank?
  end

  def self.authenticate(email, password)
    user = self.find_by_email(email)
    if user
       if user.password != password
	  user = nil
       end
    end
    user
  end 
  
  def to_s
    name
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # POST /users/search
  def search
    @query = params[:q]
    @users = User.all("name : #{@query}", :type => :fulltext)
    #@tags = Tag.all("name :#{@query}",:type => :fulltext)
    #@tag_users = Array.new
    #@tags.each do |tag|
    #     tag.use_by_user.each do |tag_user|
    #     @tag_users << tag_user
    #	 end
    # end
    @tag_users = Array.new
    @tags = Tag.find_by_name(@query)
    if @tags != nil
       @tag_users = @tags.use_by_user
    end
    if session[:user_id] != nil
       @current_user = User.find(session[:user_id])
       @is_following = Array.new
       @tag_is_following = Array.new
       @users.each do |user|
           if @current_user.following.include?(user) || @current_user.email == user.email
                @is_following[user.id.to_i] = true
           else
		@is_following[user.id.to_i] = false
           end
       end
       @tag_users.each do |tag_user|
	   if @current_user.following.include?(tag_user) || @current_user.email == tag_user.email
                @tag_is_following[tag_user.id.to_i] = true
	   else
	        @tag_is_following[tag_user.id.to_i] = false
           end
       end

    else
       @is_following = nil
    end
    
    respond_to do |format|
      format.html # search.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/all
  def all
    @users = User.all
    @isadmin = true

    respond_to do |format|
      format.html # all.html.erb
      format.json { render :json => @users }
    end
  end


  # GET /users
  # GET /users.json
  def index
    if session[:user_id] != nil
        @current_user = User.find(session[:user_id])
        @followings   = @current_user.following
        @tweets  = Array.new
        @current_user.tweets.each do |tweet|
            @tweets.push  tweet
        end
        @followings.each do |following|  
            following.tweets.each do |tweet|
               @tweets.push  tweet
            end
        end
        @tweets = @tweets.sort{|a,b|b.date.to_i <=> a.date.to_i}
    else
        respond_to do |format|
          format.html { redirect_to "/users/login" }
        end
        return
    end

    @user_name = Array.new
    @user_img = Array.new
    @user_id   = Array.new

    @tweets.each do |tweet|
        @user_id[tweet.id.to_i] = tweet.user_id
        find_user =  User.find(tweet.user_id) 
        @user_name[tweet.id.to_i] =  find_user.name
        @user_img[tweet.id.to_i] = find_user.img.nil? ? "default.png" : find_user.img
    end

    @mainpage = true
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @tweets }
    end
  end

  # GET /users/login
  def login
    respond_to do |format|
      format.html # login.html.erb
    end
  end

  # POST /users/submit_login
  def submit_login
      email = params[:email] 
      password = params[:password]
      user = User.authenticate(email,password) 
      @error = '用户名或密码错误'
      if user
	    session[:user_id] = user.id 
	    session[:user_name] = user.name 
	    redirect_to :action => 'index'
      else
        render 'users/login'
      end
  end

  # GET /users/logout
  def logout
    #TODO destroy session
    session[:user_id] = nil
    render 'users/login'  
  end


  # GET /users/tweets
  # GET /users/tweets.json
  def tweets
    @uid = params[:id]
    @user = User.find(@uid)
    @user.img = "default.png" if @user.img.nil?
    @isadmin = (session[:user_id] == @uid)
    @tweets = User.find(@uid).tweets
    @tweets = @tweets.sort{|a,b|b.date.to_i <=> a.date.to_i}
    @subhomepage = true
    respond_to do |format|
      format.html # tweets.html.erb
      format.json { render :json => @tweets }
    end
  end

  
  # GET /users/1
  # GET /users/1.json
  def show
    @uid = params[:id]
    #TODO checkdd session uid == userid
    @isadmin = (session[:user_id] == @uid)

    @user = User.find(params[:id]) #test
    @user.img = "default.png" if @user.img.nil?
    #TODO find user's tag
    @tags = @user.user_tags
    @subprofile = true
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/followers
  # GET /users/followers.json
  def followers
    @uid = params[:id]
    @user = User.find(@uid)
    @users = @user.followers
    @is_following = Array.new
    @current_user = User.find(session[:user_id])

    @users.each do |user|
      if @current_user.following.include?(user) || @current_user.email == user.email
         @is_following[user.id.to_i] = true
      else      
         @is_following[user.id.to_i] = false  
      end
    end

    @isadmin = true

    @subfollower = true
    respond_to do |format|
      format.html # followers .html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/followering
  # GET /users/followering.json
  def following
    @uid = params[:id]
    @user = User.find(params[:id])
    @users = @user.following
    @isadmin = true
    
    @is_following = Array.new
    @current_user = User.find(session[:user_id])
    
    @users.each do |user|
      if @current_user.following.include?(user) || @current_user.email == user.email
         @is_following[user.id.to_i] = true
      else
         @is_following[user.id.to_i] = false
      end
    end
    @subfollowing = true
    respond_to do |format|
      format.html # followering.html.erb
      format.json { render :json => @users}
    end
  end

  # GET /users/add_following
  def add_following
    @uid = params[:id]
    @follower = User.find(@uid)
    @user = User.find(session[:user_id])
    @users = @user.following

    if !@user.following.include?(@user)
    	@user.following << @follower
    	@follower.followers << @user
    	@user.save!
    	@follower.save!
    end

    respond_to do |format|
      format.html { redirect_to "/users/following/#{session[:user_id]}" }
      format.json { render :json => @users}
    end
  end

  # GET /users/del_follower
  def del_follower
    @uid = params[:id]
    @follower = User.find(@uid)
    @current_user = User.find(session[:user_id])
    @current_user.followers.delete(@follower)
    @follower.following.delete(@current_user)
    @current_user.save!
    @follower.save!
    @users = @current_user.followers
    respond_to do |format|
      format.html {redirect_to "/users/followers/#{session[:user_id]}"}
      format.json {render :json => @users}
    end
  end

  # GET /users/del_following
  def del_following
     @uid = params[:id]
     @following = User.find(@uid)
     @current_user = User.find(session[:user_id])
     @current_user.following.delete(@following)
     @following.followers.delete(@current_user)
     @current_user.save!
     @following.save!
     @users = @current_user.following
     respond_to do |format|
        format.html {redirect_to "/users/following/#{session[:user_id]}"}
        format.json {render :json => @users}
     end
  end


  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        session[:user_name] = @user.name
        format.html { redirect_to @user, :notice => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end


  # GET /users/upload_photo
  def upload_photo
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # POST /users/submit_upload
  def submit_upload
      directory = "public/photo"
      name = params[:upload][:file].original_filename 
      type = ""
      if(name =~ /(jpe?g|png)/i) then
          type = $1
      else
          @error = "仅支持JPG和PNG格式"
      end
      name = session[:user_id] + "." + type
      @user = User.find(session[:user_id])
      @user.img = name
      @user.save!

      path = File.join(directory, name)
      File.open(path, "wb") { |f| f.write(params[:upload][:file].read) }

      respond_to do |format|
          if @error.nil?
              format.html { redirect_to @user, :notice => '用户头像更新成功' }
              format.json { head :no_content }
          else
              format.html { render :action => "edit" }
              format.json { render :json => @error }
          end
      end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="row">
<div class="span12">
<%= form_for(@user,:html => {:class => "form-horizontal"}) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="control-group">
    <label class="control-label">邮箱</label>
    <div class="controls"><%= f.text_field :email %></div>
  </div>
  <div class="control-group">
    <label class="control-label">密码</label>
    <div class="controls"><%= f.password_field :password %></div>
  </div>
  <div class="control-group">
    <label class="control-label">昵称</label>
    <div class="controls"><%= f.text_field :name %></div>
  </div>
  <div class="control-group">
    <label class="control-label">所在地</label>
    <div class="controls"><%= f.text_field :location %></div>
  </div>
  <div class="control-group">
    <label class="control-label">性别</label>
    <div class="controls">
        <%= f.radio_button :gender, "男"%> 男
        <%= f.radio_button :gender, "女"%> 女
    </div>
  </div>
  <div class="control-group">
    <label class="control-label">博客</label>
    <div class="controls"><%= f.text_field :blog %></div>
  </div>
  <div class="control-group">
    <label class="control-label">QQ</label>
    <div class="controls"><%= f.text_field :qq %></div>
  </div>
  <div class="control-group">
    <label class="control-label">MSN</label>
    <div class="controls"><%= f.text_field :msn %></div>
  </div>                           
  <div class="control-group">
    <label class="control-label">简介</label>
    <div class="controls"><%= f.text_area :intro ,:rows => 4  %></div>
  </div>
  <div class="form-actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>
</div>
</div>

app/views/users/_navbar.html.erb
<div class="navbar">
    <div class="navbar-inner">
        <ul class="nav">
            <% if @uid == session[:user_id] then%>
                <li <% if @subhomepage then %> class="active" <%end%>><a href="/users/tweets/<%=@uid%>">我的主页</a></li>
                <li <% if @subprofile then %> class="active" <%end%>><a href="/users/<%=@uid%>">我的资料</a></li>
                <li <% if @subfollowing then %> class="active" <%end%>><a href="/users/following/<%=@uid%>">我的关注</a></li>
                <li <% if @subfollower then %> class="active" <%end%>><a href="/users/followers/<%=@uid%>">我的粉丝</a></li>
            <% else %>
                <li <% if @subhomepage then %> class="active" <%end%>><a href="/users/tweets/<%=@uid%>">TA的主页</a></li>
                <li <% if @subprofile then %> class="active" <%end%>><a href="/users/<%=@uid%>">TA的资料</a></li>
                <li <% if @subfollowing then %> class="active" <%end%>><a href="/users/following/<%=@uid%>">TA的关注</a></li>
                <li <% if @subfollower then %> class="active" <%end%>><a href="/users/followers/<%=@uid%>">TA的粉丝</a></li>
            <% end %>
        </ul>
    </div>
</div>

app/views/users/all.html.erb
<legend>所有用户</legend>
<% @users.each do |user| %>
    <div class="row">
        <div class="span1">
            <a href="/users/<%=user.id%>"><img src="http://tp2.sinaimg.cn/<%=user.id%>/50/5609049485/1" height="45" width="45" class="img-polaroid"></img></a>
            <br />
            <%= link_to user.name, user %>  
        </div>
        <div class="span11">
            <%= link_to user.name, user %>  
            <span class="time"><%= user.gender %></span>
            <%= user.location %>
            <span class="pull-right">
                <% if @isadmin then %>
                    <a href="/users/add_following/<%=user.id%>" class="btn btn-info">关注</a>
                <%end%>
            </span>
        </div> 
    </div>  
    <hr />
<% end %>

app/views/users/edit.html.erb
<legend>修改资料</legend>
<%= render 'form' %>

app/views/users/followers.html.erb
<%= render 'navbar' %>
<legend>粉丝列表</legend>
<% @users.each do |user| %>
    <div class="row">
        <div class="span1">
            <% user.img = "default.png" if user.img.nil? %>
            <a href="/users/<%=user.id%>"><img src="/photo/<%=user.img%>" height="45" width="45" class="img-polaroid"></img></a>
            <br />
            <%= link_to user.name, user %>  
        </div>
        <div class="span11">
            <span class="time"><%= user.gender %></span>
            <%= user.location %>
            <span class="pull-right">
                <% if @isadmin then %>
                <% if @is_following[user.id.to_i] == false then %>
                    <a href="/users/add_following/<%=user.id%>" class="btn btn-info">关注</a>
                <%end%>
                    <a href="/users/del_follower/<%=user.id%>" class="btn">删除</a>
                <%end%>
            </span>
        </div> 
    </div>  
    <hr />
<% end %>

app/views/users/following.html.erb
<%= render 'navbar' %>
<legend>关注列表</legend>
<% @users.each do |user| %>
    <div class="row">
        <div class="span1">
            <% user.img = "default.png" if user.img.nil? %>
            <a href="/users/<%=user.id%>"><img src="/photo/<%=user.img%>" height="45" width="45" class="img-polaroid"></img></a>
            <br />
            <%= link_to user.name, user %>  
        </div>
        <div class="span11">
            <span class="time"><%= user.gender %></span>
            <%= user.location %>
            <span class="pull-right">
                <% if @isadmin then %>
                <% if @is_following[user.id.to_i] == false then %>
                    <a href="/users/add_following/<%=user.id%>" class="btn btn-info">关注</a>
                <%end%>
                    <a href="/users/del_following/<%=user.id%>" class="btn">删除</a>
                <%end%>
            </span>
        </div> 
</div>  
<hr />
<% end %>

app/views/users/index.html.erb
<legend>发布新鲜事</legend>
<div class="row">
    <div class="span12">
            <form accept-charset="UTF-8" action="/tweets" class="new_tweet" id="new_tweet" method="post"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="✓"><input name="authenticity_token" type="hidden" value="d7epYIOWTszD/Xa8d/EEYypZBtn6nbjQoYbwn//zeso="></div>
            <textarea id="tweet_text" name="tweet[text]" rows="4" cols="100"></textarea>
        <input id="post_btn" type="submit" value="发布" class="btn btn-primary" />
    </form>
    </div>
</div>

<br />

<legend>全部微博</legend>
<% @tweets.each do |tweet| %>
<div class="row">
    <div class="span1">
        <a href="/users/<%= @user_id[tweet.id.to_i] %>"> <img src="/photo/<%= @user_img[tweet.id.to_i] %>" height="45" width="45" class="img-polaroid"></img></a>
        <br />
        <a href="/users/<%= @user_id[tweet.id.to_i] %>"><%= @user_name[tweet.id.to_i] %></a>
        
    </div>
    <div class="span8">
        <%= tweet.text %>
        <br />
        <span class="time"><%= tweet.date %></span>
        <br />
    </div>
</div>
<hr />
<br />
<% end %>

app/views/users/login.html.erb
<div class="row">
    <img style="border:1px solid grey;" src="/images/head.png" alt="banner" />
    <br />
    <br />
    <legend>登录</legend>
    <br />
    <div class="span12">
        <% unless @error.nil? then %>
            <div class="alert alert-error"> <%= @error %> </div>
        <% end %>
        <form method="post" action="/users/submit_login" class="form-horizontal">
            <div class="control-group">
                <label class="control-label">邮箱</label>
                <div class="controls"><input name="email" type="text" /></div>
            </div>
            <div class="control-group">
                <label class="control-label">密码</label>
                <div class="controls"><input name="password" type="password" /></div>
            </div>
            <div class="form-actions">
                <input type="submit" class="btn btn-primary" value="登录" />
            </div>
        </form>
    </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="span12">
    <legend>用户注册</legend>
    <%= render 'form' %>
    <%= link_to '直接登录', users_path %>
  </div>
</div>

app/views/users/search.html.erb
<legend>"<%=@query%>" 用户查询结果</legend>
<% if !@users.nil? && @users.count > 0 then %>
<% @users.each do |user| %>
    <div class="row">
        <div class="span1">
            <% user.img = "default.png" if user.img.nil? %>
            <a href="/users/<%=user.id%>" ><img src="/photo/<%= user.img %>" height="45" width="45" class="img-polaroid"></img> </a>
        </div>
        <div class="span11">
            <%= link_to user.name, user %>  
            <span class="time"><%= user.gender %></span>
            <%= user.location %>
            <% if user.id != session[:user_id] then %>
                <span class="pull-right">
                    <% if @is_following != nil && @is_following[user.id.to_i] == false then %>
                        <a href="/users/add_following/<%=user.id%>" class="btn btn-info">关注</a>
                    <% elsif @is_following != nil then %>
                        <a href="/users/del_following/<%=user.id%>" class="btn btn-info">删除</a>
                    <%end%>
                </span>
            <% end %>
        </div> 
    </div>  
    <hr />
<% end %>
<% else %>
    <div class="alert alert-error">
        抱歉，没有任何查询结果  
    </div>
<% end %>

<legend>包含标签"<%=@query%>"的用户</legend>
<% if !@tag_users.nil? && @tag_users.count > 0 then %>
    <% @tag_users.each do |user| %>
        <div class="row">
            <div class="span1">
                <% user.img = "default.png" if user.img.nil? %>
                <a href="/users/<%=user.id%>" ><img src="/photo/<%= user.img %>" height="45" width="45" class="img-polaroid"></img> </a>
            </div>
            <% if user.id != session[:user_id] then %>
            <div class="span11">
                <%= link_to user.name, user %>  
                <span class="time"><%= user.gender %></span>
                <%= user.location %>
                <span class="pull-right">
                    <% if @tag_is_following != nil && @tag_is_following[user.id.to_i] == false then %>
                        <a href="/users/add_following/<%=user.id%>" class="btn btn-info">关注</a>
                    <% elsif @tag_is_following != nil then %>
                        <a href="/users/del_following/<%=user.id%>" class="btn btn-info">删除</a>
                    <%end%>
                </span>
                <% end %>
        </div> 
            </div> 
        </div>  
        <hr />
    <% end %>
<% else %>
    <div class="alert alert-error">
        抱歉，没有任何用户使用了该标签.  
    </div>
<% end %>       

app/views/users/show.html.erb
<%= render 'navbar' %>
<% unless notice.nil?  then %>
<div class="alert alert-block">
    <p id="notice"><%= notice %></tr>
</div>
<% end %>

<div class="row-fluid">
    <div class="span2">
        <a href="/users/upload_photo">
            <img src="/photo/<%= @user.img%>" height="100" width="100" class="thumbnail">
         </a> 
    </div>
    <div class="span10">
    <legend>基本信息</legend>
    <table class="table table-bordered table-hover">
        <tr>
        <td><b>昵称:</b></td>
        <td><%= @user.name %></td>
        </tr>

        <tr>
        <td><b>邮箱:</b></td>
        <td><%= @user.email %></td>
        </tr>


        <tr>
        <td><b>所在地:</b></td>
        <td><%= @user.location %></td>
        </tr>

        <tr>
        <td><b>性别:</b></td>
        <td><%= @user.gender %></td>
        </tr>

        <tr>
        <td><b>博客:</b></td>
        <td><%= @user.blog %></td>
        </tr>


        <tr>
        <td><b>QQ:</b></td>
        <td><%= @user.qq %></td>
        </tr>

        <tr>
        <td><b>MSN:</b></td>
        <td><%= @user.msn %></td>
        </tr>
 </table> 
        <legend>简介</legend>
        <pre><%= @user.intro %></pre>
        
        <!-- this is the hashtag area -->
        <div>
            <% if !@tags.nil? then  @tags.each do |tag| %> 
                <span class="label label-info"><%= tag.name %></span>  
            <% end end %>
        </div>


        <% if(@isadmin) %>
            <%= link_to '编辑', edit_user_path(@user), :class => "btn pull-right"%>
            &nbsp;&nbsp; &nbsp;&nbsp;
            <%= link_to '新建标签', new_tag_path(), :class => "btn pull-right"%>
        <% end %>


    </div>
</div>

app/views/users/tweets.html.erb
<%= render 'navbar' %>
<legend>微博列表</legend>
<% unless @tweets.nil? then %>
<% @tweets.each do |tweet| %>
<div class="row">
    <div class="span1">
        <a href="/users/<%= @user.id %>"> <img src="/photo/<%= @user.img %>" height="45" width="45" class="img-polaroid"></img></a>
        <br/>
        <%= link_to @user.name, @user %>  
    </div>
    <div class="span8">
        <%= tweet.text %>
        <br />
        <span class="time"><%= tweet.date %></span>
        <br />
        <% if @isadmin then %><span><%= link_to '删除', tweet, :method => :delete, :data => { :confirm => 'Are you sure?' } %></span> <% end %>
    </div>
</div>
<hr />
<br />
<% end %>   
<% else %> 
    <p>还未发过任何微博.</p>
<% end %>

app/views/users/upload_photo.html.erb
<div class="row">
    <div class="span12">
        <% if @error then%>
            <div class="alert"><%= @error %> </div>
        <% end  %>
    </div>
</div>
<div class="row">
    <div class="span12">
        <legend>上传头像</legend>
        <%= form_tag('/users/submit_upload', {:class => "form-horizontal", :mutipart => true, :enctype => "multipart/form-data"}) do %>
            <div class="control-group">
                <label class="control-label">头像文件:</label>
                <div class="controls"><%= file_field_tag 'upload[file]' %></div>
            </div>

            <div class="form-actions">
                <%= submit_tag "确认上传", :class => "btn btn-primary" %>
            </div>
        <% end %>
    </div>
</div>