config/routes.rb
Weibo::Application.routes.draw do
  resources :tags

  match 'users/upload_photo' => 'users#upload_photo'
  match 'users/submit_upload' => 'users#submit_upload', :via => 'post'
  match 'users/login' => 'users#login'
  match 'users/submit_login' => 'users#submit_login', :via => 'post'
  match 'users/logout' => 'users#logout'
  match 'users/tweets/:id' => 'users#tweets'
  match 'users/followers/:id' => 'users#followers'
  match 'users/follower/:id' => 'users#followers'
  match 'users/following/:id' => 'users#following'
  match 'users/followings/:id' => 'users#following'
  match 'users/add_following/:id' => 'users#add_following'
  match 'users/del_follower/:id' => 'users#del_follower'
  match 'users/del_following/:id' => 'users#del_following'
  match 'users/all' => 'users#all'
  match 'users/search' => 'users#search'
 
  resources :tags
  resources :tweets
  resources :users

  root :to => 'users#index'

end

app/models/tag.rb
class Tag < Neo4j::Rails::Model
  property :name, :type => String, :index => :exact

  has_n(:use_by_user).from(:user_tags)

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.json
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.json
  def create
    @user = User.find(session[:user_id]) 
    if Tag.find_by_name(params[:tag][:name]) == nil
   	@tag = Tag.new(params[:tag])
	@user.user_tags << @tag
        @tag.save!
        @user.save!
    else 
        @tag = Tag.find_by_name(params[:tag][:name])
	if !@user.user_tags.include?(@tag)
        	@user.user_tags << @tag
        	@user.save!
	end
    end
    

    #TODO 绑定到session userid
    @uid = session[:user_id]
    respond_to do |format|
      if @tag.save
        #format.html { redirect_to @tag, :notice => 'Tag was successfully created.' }
        format.html { redirect_to "/users/#{session[:user_id]}" }
        format.json { render :json => @tag, :status => :created, :location => @tag }
      else
        format.html { render :action => "new" }
        format.json { render :json => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.json
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to @tag, :notice => 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for(@tag, :html => {:class => "form-horizontal"}) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
      <label class="control-label">标签:</label>
      <div class="controls"><%= f.text_field :name %></div>
  </div>

  <div class="alert">
      <strong>提醒</strong> 定义更多的标签能让其他人通过标签找到你，你也可以找到更多志同道合的朋友。
  </div>

  <div class="form-actions">
      <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Listing tags</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tags.each do |tag| %>
  <tr>
    <td><%= tag.name %></td>
    <td><%= link_to 'Show', tag %></td>
    <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
    <td><%= link_to 'Destroy', tag, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<div class="row">
<div class="span12">
<legend>添加一个标签</legend>
<%= render 'form' %>
<%= link_to 'Back', users_path %>
  </div>
</div>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tag.name %>
</p>


<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>